export default {
  'day-01-cold-start': 'Day 01 — Cold start',
  'day-02-joint-foc': 'Day 02 — Joint FOC',
  'day-03-sensing-beyond-joint': 'Day 03 — Sensing beyond the joint',
  'day-04-bus-time-sync': 'Day 04 — Bus & time sync',
  'day-05-power-bms': 'Day 05 — Power & BMS',
  'day-06-estimation-balance': 'Day 06 — Estimation & balance',
  'day-07-wbc-balance': 'Day 07 — WBC & balance',
  'day-08-stepping-locomotion': 'Day 08 — Stepping & locomotion',
  'day-09-push-recovery': 'Day 09 — Push recovery',
  'day-10-upper-body-manipulation': 'Day 10 — Upper-body manipulation',
  'day-11-hand-support-loco-manipulation': 'Day 11 — Hand-as-support / loco-manipulation',
  'day-12-multicontact-transitions': 'Day 12 — Multi-contact transitions / object-as-support',
  'day-13-support-affordances': 'Day 13 — Perception-driven support affordances',
  'day-14-learned-residuals-scene-graphs': 'Day 14 — Learned residuals / scene graphs',
  'day-15-closed-loop-learned-policies': 'Day 15 — Closed-loop learned policies',
  'day-16-teleop-shared-autonomy': 'Day 16 — Teleop / shared-autonomy arbitration',
  'day-17-runtime-safety-supervisor': 'Day 17 — Runtime safety supervisor / kill-chain',
  'day-18-teleop-policy-logging-replay': 'Day 18 — Teleop+policy logging / replay / dataset hygiene',
  'day-19-offline-eval-shadow-canary': 'Day 19 — Offline eval / shadow mode / canary under supervisor + logging gates',
  'day-20-hil-regression-farm': 'Day 20 — HIL regression farm under supervisor + logging + canary gates',
  'day-21-fleet-continual-learning': 'Day 21 — Fleet multi-robot logging / ticket-log sync / online continual learning',
  'day-22-fleet-canary-orchestration': 'Day 22 — Fleet canary orchestration / multi-site sim-to-real ranking',
  'day-23-fleet-incident-response': 'Day 23 — Fleet incident response / coordinated rollback / multi-robot kill',
  'day-24-post-incident-forensics': 'Day 24 — Post-incident forensics / fleet postmortem bags / reopen canary'
}
